# Generated by Django 5.0 on 2024-05-17 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.TextField(choices=[('Інше', 'Інше'), ('Дисертація', 'Дисертація'), ('Публікації', 'Публікації'), ('План наукової роботи', 'План наукової роботи'), ('Навчальний план', 'Навчальний план')], default='Інше')),
                ('description', models.TextField()),
                ('is_active', models.CharField(choices=[('Активний', 'Активний'), ('Не активний', 'Не активний')], default='Активний', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abbreviation', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abstract', models.TextField(verbose_name='Анотація')),
                ('council_cypher', models.CharField(max_length=20)),
                ('defense_date', models.DateField(verbose_name='Дата захисту')),
                ('defense_link', models.URLField(blank=True, default='https://www.link.com')),
                ('state', models.CharField(choices=[('0%', '0%'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], default='0%', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('issn_electronic', models.CharField(max_length=15)),
                ('issn_printed', models.CharField(max_length=15)),
                ('isbn_electronic', models.CharField(max_length=15)),
                ('isbn_printed', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.CharField(choices=[('Так', 'Так'), ('Ні', 'Ні')], default='Ні', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgraduateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=55)),
                ('firstname', models.CharField(max_length=55)),
                ('middlename', models.CharField(max_length=55)),
                ('gender', models.CharField(choices=[('Чоловіча', 'Чоловіча'), ('Жіноча', 'Жіноча')], default='Чоловіча', max_length=15)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('scientific_profile', models.URLField(blank=True, default='https://www.scopus.com')),
                ('status', models.CharField(choices=[('Навчається', 'Навчається'), ('Відрахований(-а)', 'Відрахований(-а)'), ('Академвідпустка', 'Академвідпустка')], default='Навчається', max_length=25)),
                ('learning_source', models.CharField(choices=[('Бюджет', 'Бюджет'), ('Контракт', 'Контракт')], default='Бюджет', max_length=15)),
                ('is_graduate', models.CharField(choices=[('Так', 'Так'), ('Ні', 'Ні')], default='Ні', max_length=5)),
                ('is_defended', models.CharField(choices=[('Захист відсутній', 'Захист відсутній'), ('Рекомендований(-а) до захисту', 'Рекомендований(-а) до захисту'), ('Захистився(-лась)', 'Захистився(-лась)'), ('Не захистився(-лась)', 'Не захистився(-лась)')], default='Захист відсутній', max_length=35)),
                ('is_approved', models.CharField(choices=[('Очікується перевірка', 'Очікується перевірка'), ('Затверджено', 'Затверджено'), ('Не затверджено', 'Не затверджено')], default='Очікується перевірка', max_length=25)),
                ('messaging_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.CharField(max_length=5)),
                ('area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=55)),
                ('firstname', models.CharField(max_length=55)),
                ('middlename', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('academic_status', models.CharField(choices=[('Асистент', 'Асистент'), ('Доктор філософії', 'Доктор філософії'), ('Доктор наук', 'Доктор наук'), ('Доцент', 'Доцент'), ('Старший дослідник', 'Старший дослідник'), ('Професор', 'Професор')], default='Професор', max_length=20)),
                ('scientific_profile', models.URLField(blank=True, default='https://www.scopus.com')),
            ],
        ),
        migrations.CreateModel(
            name='DissertationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_state', models.CharField(choices=[('0%', '0%'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], default='0%', max_length=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('dissertation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='phdc_app.dissertation')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.CharField(choices=[('Так', 'Так'), ('Ні', 'Ні')], default='Ні', max_length=5)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.notifications')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.postgraduatestudent')),
            ],
        ),
        migrations.CreateModel(
            name='EducIndPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.TextField()),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=5)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=5)),
                ('dis_type', models.CharField(choices=[('Іспит', 'Іспит'), ('Екзамен', 'Екзамен'), ('Залік', 'Залік')], default='іспит', max_length=10)),
                ('dis_credit', models.CharField(default='1', max_length=5)),
                ('attestation_form', models.CharField(default='залік', max_length=20)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educ_plans', to='phdc_app.postgraduatestudent')),
            ],
        ),
        migrations.AddField(
            model_name='dissertation',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissertation', to='phdc_app.postgraduatestudent'),
        ),
        migrations.CreateModel(
            name='DeadlineSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.deadline')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.postgraduatestudent')),
            ],
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('Інше', 'Інше'), ('Дисертація', 'Дисертація'), ('Публікації', 'Публікації'), ('План наукової роботи', 'План наукової роботи'), ('Навчальний план', 'Навчальний план')], default='Інше')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlblacklist', to='phdc_app.deadline')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentblacklist', to='phdc_app.postgraduatestudent')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('department_decision', models.TextField()),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='dissertation',
            name='protocol_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.protocol'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('volume', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=5)),
                ('pages', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('doi', models.URLField(blank=True, default='https://www.link.com')),
                ('is_suitable', models.CharField(choices=[('Очікується перевірка', 'Очікується перевірка'), ('Зараховано', 'Зараховано'), ('Не зараховано', 'Не зараховано')], default='Очікується', max_length=20)),
                ('coef', models.CharField(choices=[('Відсутній', 'Відсутній'), ('0.5', '0.5'), ('0.25', '0.25')], default='Відсутній', max_length=15)),
                ('edition_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='phdc_app.edition')),
                ('protocol_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.protocol')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.publicationtypes')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchIndPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField(default='Відсутній')),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=5)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=5)),
                ('date_sem_start', models.DateField()),
                ('date_sem_end', models.DateField()),
                ('impl_form', models.TextField(default='Відсутня')),
                ('protocol_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.protocol')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_plans', to='phdc_app.postgraduatestudent')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(verbose_name='Опис')),
                ('date_start', models.DateField(verbose_name='Дата початку')),
                ('date_end', models.DateField(default='2024-09-12', verbose_name='Дата кінця')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.seminar')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.postgraduatestudent')),
            ],
        ),
        migrations.CreateModel(
            name='EditionSpecialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.edition')),
                ('specialty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=5)),
                ('study_type', models.CharField(choices=[('Денна', 'Денна'), ('Вечірня', 'Вечірня'), ('Дистанційна', 'Дистанційна'), ('Очна', 'Очна')], default='Денна', max_length=15)),
                ('date_educ_start', models.DateField(verbose_name='Початок навчання')),
                ('date_educ_end', models.DateField(verbose_name='Кінець навчання')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.department')),
                ('specialty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.specialty')),
            ],
        ),
        migrations.AddField(
            model_name='postgraduatestudent',
            name='study_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='phdc_app.studygroup'),
        ),
        migrations.CreateModel(
            name='Reviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissertation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phdc_app.dissertation')),
                ('reviewer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='phdc_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='postgraduatestudent',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.teacher'),
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentauth', to='phdc_app.postgraduatestudent')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubauth', to='phdc_app.publication')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherauth', to='phdc_app.teacher')),
            ],
        ),
    ]
