# Generated by Django 5.0 on 2024-05-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='date_end',
            field=models.DateField(verbose_name='Дата кінця'),
        ),
    ]
