# Generated by Django 5.0 on 2024-05-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0002_alter_seminar_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacherauth', to='phdc_app.teacher'),
        ),
        migrations.AlterField(
            model_name='researchindplan',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_plans', to='phdc_app.postgraduatestudent'),
        ),
    ]
