# Generated by Django 5.0 on 2024-05-21 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0003_alter_authors_teacher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='specialty_id',
        ),
        migrations.AddField(
            model_name='postgraduatestudent',
            name='specialty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.specialty'),
        ),
    ]
