# Generated by Django 5.0 on 2024-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0004_remove_studygroup_specialty_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='date_start',
        ),
        migrations.AddField(
            model_name='seminar',
            name='date',
            field=models.DateField(default='2024-01-01', verbose_name='Дата проведення'),
        ),
    ]
