# Generated by Django 5.0 on 2024-05-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0006_deadlinesubmission_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='category',
            field=models.TextField(choices=[('Інше', 'Інше'), ('Дисертація', 'Дисертація'), ('Публікації', 'Публікації'), ('План наукової роботи', 'План наукової роботи'), ('Навчальний план', 'Навчальний план'), ('Дедлайни', 'Дедлайни')], default='Інше'),
        ),
    ]
