# Generated by Django 5.0 on 2024-05-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0007_alter_blacklist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
