# Generated by Django 5.0 on 2024-05-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0010_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phdc_app.studygroup'),
        ),
    ]
