# Generated by Django 5.0 on 2024-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0012_publication_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='educindplan',
            name='is_approved',
            field=models.CharField(choices=[('Очікується перевірка', 'Очікується перевірка'), ('Затверджено', 'Затверджено'), ('Не затверджено', 'Не затверджено')], default='Очікується перевірка', max_length=25),
        ),
    ]
