# Generated by Django 5.0 on 2024-05-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0014_researchindplan_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='status',
        ),
        migrations.AddField(
            model_name='protocol',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(),
        ),
    ]
