# Generated by Django 5.0 on 2024-05-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0015_remove_email_status_protocol_file_alter_email_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgraduatestudent',
            name='is_defended',
            field=models.CharField(choices=[('Захист відсутній', 'Захист відсутній'), ('Рекомендований(-а)', 'Рекомендований(-а)'), ('Захистився(-лась)', 'Захистився(-лась)'), ('Не захистився(-лась)', 'Не захистився(-лась)')], default='Захист відсутній', max_length=35),
        ),
    ]
