# Generated by Django 5.0 on 2024-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0016_alter_postgraduatestudent_is_defended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='study_type',
            field=models.CharField(choices=[('Денна', 'Денна'), ('Вечірня', 'Вечірня'), ('Дистанційна', 'Дистанційна'), ('Очна', 'Очна'), ('Заочна', 'Заочна')], default='Денна', max_length=15),
        ),
    ]
