# Generated by Django 5.0 on 2024-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0017_alter_studygroup_study_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='coef',
            field=models.CharField(choices=[('0', '0'), ('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2')], default='0', max_length=15),
        ),
    ]
