# Generated by Django 5.0 on 2024-05-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0018_alter_publication_coef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_suitable',
            field=models.CharField(choices=[('Очікується перевірка', 'Очікується перевірка'), ('Зарахована', 'Зарахована'), ('Не зарахована', 'Не зарахована')], default='Очікується', max_length=20),
        ),
    ]
