# Generated by Django 5.0 on 2024-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0019_alter_publication_is_suitable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educindplan',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='researchindplan',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='educindplan',
            name='attestation_form',
            field=models.CharField(choices=[('Іспит', 'Іспит'), ('Екзамен', 'Екзамен'), ('Залік', 'Залік')], default='Залік', max_length=10),
        ),
        migrations.AlterField(
            model_name='educindplan',
            name='dis_type',
            field=models.CharField(choices=[('Нормативна', 'Нормативна'), ('Вибіркова', 'Вибіркова')], default='Нормативна', max_length=10),
        ),
        migrations.AlterField(
            model_name='educindplan',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='researchindplan',
            name='semester',
            field=models.CharField(choices=[('Осінній', 'Осінній'), ('Весняний', 'Весняний')], default='Осінній', max_length=15),
        ),
    ]
