# Generated by Django 5.0 on 2024-06-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0022_researchindplan_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchindplan',
            name='name',
        ),
    ]
