# Generated by Django 5.0 on 2024-06-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0023_remove_researchindplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchindplan',
            name='date_sem_end',
            field=models.DateField(verbose_name='Кінець семестру'),
        ),
        migrations.AlterField(
            model_name='researchindplan',
            name='date_sem_start',
            field=models.DateField(verbose_name='Початок семестру'),
        ),
    ]
