# Generated by Django 5.0 on 2024-06-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0024_alter_researchindplan_date_sem_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='protocol_id',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='department_decision',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='file',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='protocol_id',
        ),
        migrations.RemoveField(
            model_name='researchindplan',
            name='protocol_id',
        ),
        migrations.AddField(
            model_name='protocol',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='phdc_app.postgraduatestudent'),
        ),
    ]
