# Generated by Django 5.0 on 2024-06-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0025_remove_dissertation_protocol_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgraduatestudent',
            name='messaging_time',
        ),
    ]
