# Generated by Django 5.0 on 2024-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0029_alter_protocol_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typo', models.CharField(choices=[('Зарахування', 'Зарахування'), ('Відрахування', 'Відрахування'), ('Відновлення', 'Відновлення'), ('Академ відпустка', 'Академ відпустка')])),
                ('number', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
