# Generated by Django 5.0 on 2024-06-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0030_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='student_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='phdc_app.postgraduatestudent'),
        ),
    ]
