# Generated by Django 5.0 on 2024-06-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdc_app', '0031_order_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('student_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='phdc_app.postgraduatestudent')),
            ],
        ),
    ]
